#!/bin/sh
pgrep -x sxhkd > dev/null || sxhkd &
pgrep -x lxsession > dev/null || lxsession &
wal -o ~/.config/wal/done.sh -i $HOME/Pictures/Wallpapers &
pgrep -x picom > dev/null || picom &
xrdb ~/.Xresources
