#!/bin/sh
# Applications
#feh --bg-scale --randomize $HOME/Pictures/Wallpapers
dwall -s street &
pgrep conky || ~/.config/conky/start-conky.sh &
xrdb ~/.Xresources

mpd-mpris &
pgrep bspswallow || ~/.local/scripts/bspswallow &

~/.local/scripts/lock.py &

xfce4-power-manager &
