#!/bin/sh
wal -o ~/.config/wal/done.sh -i $HOME/Pictures/Wallpapers &
pgrep conky || ~/.config/conky/start-conky.sh &
xrdb ~/.Xresources

mpd-mpris &
pgrep bspswallow || ~/.local/scripts/bspswallow &

~/.local/scripts/lock.py &

xfce4-power-manager &
